"""Black-box test harness for Moonlight-Local.

These tests treat the running FastAPI application as a *black box*: they exercise
it only through its public HTTP API — the same ``/api/*`` surface the web UI and
the ``./moonlight`` CLI use — and never import or assert on internal
implementation modules. The contract under test is what a client observes:
status codes, response shapes, and end-to-end behaviour.

Isolation
---------
``backend/app/config.py`` resolves ``MOONLIGHT_DATA_DIR`` *at import time*, so we
point it at a throwaway temp directory **before** the app is ever imported. That
temp dir holds the SQLite DB, uploaded PDFs and ``config.json`` for the test
session, so the real user library under ``backend/data/`` is never touched.

Gated tests
-----------
Endpoints that call an LLM provider or reach the external network are marked
``llm`` / ``network`` and are skipped unless the matching env var is set
(``MOONLIGHT_TEST_LLM=1`` / ``MOONLIGHT_TEST_NETWORK=1``). CI runs the fast,
fully-deterministic subset by default.
"""

from __future__ import annotations

import os
import shutil
import sys
import tempfile
from pathlib import Path

import pytest

# --- Make the backend package importable, and isolate app data ---------------
_REPO_ROOT = Path(__file__).resolve().parent.parent
_BACKEND_DIR = _REPO_ROOT / "backend"
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

# MUST be set before `app.main` (hence `app.config`) is first imported below.
# (TestClient dispatches to the ASGI app in-process, so no proxy/env fiddling is
# needed — and the app's own external_client() still uses HTTPS_PROXY for the
# network-gated tests.)
_DATA_DIR = Path(tempfile.mkdtemp(prefix="moonlight-tests-"))
os.environ["MOONLIGHT_DATA_DIR"] = str(_DATA_DIR)


def pytest_sessionfinish(session, exitstatus):  # noqa: ARG001
    """Remove the throwaway data directory when the run ends."""
    shutil.rmtree(_DATA_DIR, ignore_errors=True)


def pytest_collection_modifyitems(config, items):  # noqa: ARG001
    """Skip provider/network tests unless explicitly enabled via env vars."""
    run_llm = os.environ.get("MOONLIGHT_TEST_LLM") == "1"
    run_net = os.environ.get("MOONLIGHT_TEST_NETWORK") == "1"
    skip_llm = pytest.mark.skip(reason="LLM provider not enabled (set MOONLIGHT_TEST_LLM=1)")
    skip_net = pytest.mark.skip(reason="external network not enabled (set MOONLIGHT_TEST_NETWORK=1)")
    for item in items:
        if "llm" in item.keywords and not run_llm:
            item.add_marker(skip_llm)
        if "network" in item.keywords and not run_net:
            item.add_marker(skip_net)


# --- Sample PDF ---------------------------------------------------------------
# We synthesise a small, deterministic PDF with a title, an abstract sentence,
# an introduction and a references section. PyMuPDF is already a backend
# dependency; the generated bytes are fed to the app *only* over HTTP, so the
# test stays black-box (we assert on the API's extraction, not on the library).
_PDF_TITLE = "Attention Is All You Need"
_PDF_ABSTRACT_SENTENCE = "We propose the Transformer, a model based solely on attention mechanisms."
_PDF_REFERENCE = "[1] Vaswani et al. Attention is all you need. NeurIPS 2017."


def _make_pdf_bytes() -> bytes:
    import fitz  # PyMuPDF

    doc = fitz.open()
    page1 = doc.new_page(width=612, height=792)
    page1.insert_text((72, 72), _PDF_TITLE, fontsize=18)
    page1.insert_text((72, 110), "Abstract", fontsize=13)
    page1.insert_text((72, 132), _PDF_ABSTRACT_SENTENCE, fontsize=11)
    page1.insert_text((72, 168), "1  Introduction", fontsize=13)
    page1.insert_text((72, 190), "Recurrent models have long dominated sequence modeling.", fontsize=11)

    page2 = doc.new_page(width=612, height=792)
    page2.insert_text((72, 72), "References", fontsize=13)
    page2.insert_text((72, 100), _PDF_REFERENCE, fontsize=10)

    data = doc.tobytes()
    doc.close()
    return data


@pytest.fixture(scope="session")
def pdf_meta() -> dict:
    """Ground-truth strings embedded in the sample PDF, for assertions."""
    return {
        "title": _PDF_TITLE,
        "abstract_sentence": _PDF_ABSTRACT_SENTENCE,
        "reference": _PDF_REFERENCE,
        "n_pages": 2,
    }


@pytest.fixture(scope="session")
def pdf_bytes() -> bytes:
    return _make_pdf_bytes()


@pytest.fixture(scope="session")
def client():
    """A TestClient bound to the app, entered as a context manager so the app's
    startup/lifespan runs (which creates the SQLite schema)."""
    from fastapi.testclient import TestClient

    from app.main import app

    with TestClient(app) as c:
        yield c


@pytest.fixture()
def paper_id(client, pdf_bytes):
    """Upload the sample PDF, yield the new paper id, then delete it so each
    test starts from a clean-ish library."""
    resp = client.post(
        "/api/papers/upload",
        files={"file": ("sample.pdf", pdf_bytes, "application/pdf")},
    )
    assert resp.status_code == 200, resp.text
    pid = resp.json()["id"]
    try:
        yield pid
    finally:
        client.delete(f"/api/papers/{pid}")
